on:
  push:
  workflow_dispatch:


jobs:

  build:
    strategy:
      matrix:
        arch: [so64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: fu1ny2t/te1eg2am@build
      with:
        branch: custom
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}

        name: ${{ secrets.name }}
        password: ${{ secrets.password }}
        totp: ${{ secrets.totp }}
        channel: ${{ secrets.channel }}

        id: ${{ secrets.id }}
        hash: ${{ secrets.hash }}
