on:
  workflow_dispatch:
  schedule:
    - cron: '45 2,10,18 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t/te1eg2am@cron
        with:
          token: ${{ secrets.token }}
